import {
  BarChart3,
  Bot,
  Building2,
  CalendarDays,
  Car,
  ClipboardList,
  CreditCard,
  FileText,
  Hotel,
  Inbox,
  LayoutDashboard,
  Map,
  MessageSquare,
  PieChart,
  Settings,
  ShieldCheck,
  Ticket,
  Users,
  type LucideIcon,
} from 'lucide-react';
import type { VendorOSModule, VendorOSModuleDefinition } from './types';

export interface VendorOSNavItem extends VendorOSModuleDefinition {
  icon: LucideIcon;
  metric?: string;
}

export const vendorOSModules: VendorOSNavItem[] = [
  {
    id: 'dashboard',
    label: 'Overview',
    description: 'Daily pulse, actions, alerts, and operational health.',
    path: '/vendor/os',
    category: 'core',
    icon: LayoutDashboard,
    metric: 'Live',
  },
  {
    id: 'crm',
    label: 'CRM',
    description: 'Leads, guests, customers, follow-ups, and sales tasks.',
    path: '/vendor/os/crm',
    category: 'commerce',
    icon: MessageSquare,
    metric: '18 leads',
  },
  {
    id: 'calendar',
    label: 'Calendar',
    description: 'Unified bookings, capacity, availability, and departures.',
    path: '/vendor/os/calendar',
    category: 'operations',
    icon: CalendarDays,
    metric: '42 events',
  },
  {
    id: 'inbox',
    label: 'Inbox',
    description: 'Traveler messages, supplier conversations, and service notes.',
    path: '/vendor/os/inbox',
    category: 'operations',
    icon: Inbox,
    metric: '7 open',
  },
  {
    id: 'accounting',
    label: 'Accounting',
    description: 'Invoices, expenses, payouts, tax reports, and ledger controls.',
    path: '/vendor/os/accounting',
    category: 'admin',
    icon: CreditCard,
    metric: 'INR 2.8L',
  },
  {
    id: 'team',
    label: 'Team',
    description: 'Staff, branch roles, invitations, and access control.',
    path: '/vendor/os/team',
    category: 'admin',
    icon: Users,
    metric: '9 users',
  },
  {
    id: 'pms',
    label: 'PMS',
    description: 'Properties, rooms, housekeeping, check-ins, and guest documents.',
    path: '/vendor/os/pms',
    category: 'operations',
    icon: Hotel,
    metric: '83% occ',
  },
  {
    id: 'tours',
    label: 'Tours',
    description: 'Itineraries, departures, guides, manifests, and DMC operations.',
    path: '/vendor/os/tours',
    category: 'operations',
    icon: Map,
    metric: '12 trips',
  },
  {
    id: 'activities',
    label: 'Activities',
    description: 'Slots, safety logs, equipment, waivers, and guide assignment.',
    path: '/vendor/os/activities',
    category: 'operations',
    icon: Ticket,
    metric: '31 slots',
  },
  {
    id: 'fleet',
    label: 'Fleet',
    description: 'Vehicles, drivers, permits, fuel, maintenance, and assignments.',
    path: '/vendor/os/fleet',
    category: 'operations',
    icon: Car,
    metric: '14 units',
  },
  {
    id: 'ai_assistant',
    label: 'AI Assistant',
    description: 'Ops insights, suggested replies, pricing signals, and alerts.',
    path: '/vendor/os/ai-assistant',
    category: 'core',
    icon: Bot,
    metric: '5 ideas',
  },
  {
    id: 'marketplace',
    label: 'Marketplace',
    description: 'Tripetrip listings, deals, direct booking sync, and promotions.',
    path: '/vendor/os/marketplace',
    category: 'commerce',
    icon: ClipboardList,
    metric: '24 live',
  },
  {
    id: 'subscriptions',
    label: 'Subscriptions',
    description: 'Plan, billing status, usage, add-ons, and limits.',
    path: '/vendor/os/subscriptions',
    category: 'admin',
    icon: ShieldCheck,
    metric: 'Growth',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    description: 'Revenue, occupancy, conversion, category, and branch reporting.',
    path: '/vendor/os/analytics',
    category: 'commerce',
    icon: PieChart,
    metric: '+18%',
  },
  {
    id: 'branches',
    label: 'Branches',
    description: 'Properties, offices, activity bases, depots, and destination desks.',
    path: '/vendor/os/branches',
    category: 'admin',
    icon: Building2,
    metric: '3 sites',
  },
  {
    id: 'documents',
    label: 'Documents',
    description: 'KYC, permits, contracts, insurance, guest records, and vouchers.',
    path: '/vendor/os/documents',
    category: 'admin',
    icon: FileText,
    metric: '12 files',
  },
  {
    id: 'settings',
    label: 'Settings',
    description: 'Business profile, module settings, policies, and integrations.',
    path: '/vendor/os/settings',
    category: 'admin',
    icon: Settings,
    metric: 'Ready',
  },
];

export const modulePathMap: Record<string, VendorOSModule> = {
  crm: 'crm',
  calendar: 'calendar',
  inbox: 'inbox',
  accounting: 'accounting',
  team: 'team',
  pms: 'pms',
  tours: 'tours',
  activities: 'activities',
  fleet: 'fleet',
  'ai-assistant': 'ai_assistant',
  marketplace: 'marketplace',
  subscriptions: 'subscriptions',
  analytics: 'analytics',
  branches: 'branches',
  documents: 'documents',
  settings: 'settings',
};

export function getVendorOSModuleByPath(moduleParam?: string) {
  return moduleParam ? modulePathMap[moduleParam] || 'dashboard' : 'dashboard';
}
